In [2]:
pip install torch

     |████████████████████████████████| 147.1 MB 5.0 MB/s eta 0:00:012
Note: you may need to restart the kernel to use updated packages.


# 1-1

## tensor dtype & type() & ndimension() & size()

In [23]:
import torch

In [15]:
zero_D_var = torch.tensor(3)#tensor Tensor皆可
print('zero_D_var')
print(zero_D_var)
print(zero_D_var.dtype)
print(zero_D_var.type())
print(zero_D_var.ndimension())
print(zero_D_var.size())
print('-'*50)

one_D_var = torch.Tensor([3.0,5.0,8.0,9.0])
print('one_D_var')
print(one_D_var)
print(one_D_var.dtype)
print(one_D_var.type())
print(one_D_var.ndimension())
print(one_D_var.size())
print('-'*50)

two_D_var = torch.tensor([[3.0],
                          [4]],dtype=torch.float64)
print('two_D_var')
print(two_D_var)
print(two_D_var.dtype)
print(two_D_var.type())
print(two_D_var.ndimension())
print(two_D_var.size())

zero_D_var
tensor(3)
torch.int64
torch.LongTensor
0
torch.Size([])
--------------------------------------------------
one_D_var
tensor([3., 5., 8., 9.])
torch.float32
torch.FloatTensor
1
torch.Size([4])
--------------------------------------------------
two_D_var
tensor([[3.],
        [4.]], dtype=torch.float64)
torch.float64
torch.DoubleTensor
2
torch.Size([2, 1])


In [25]:
print('1-D to 2-D')
one_D = torch.tensor([1,2,3])
print(one_D)
print('1D_Dimension:',one_D.ndimension())
print('1D_Size:',one_D.size())
print('-'*50)
two_D = one_D.view(1,-1)
print(two_D)
print('2D_Dimension:',two_D.ndimension())
print('2D_Size:',two_D.size())
print('-'*50)
two_D_ = one_D.view(-1,1)
print(two_D_)
print('2D_Dimension:',two_D_.ndimension())
print('2D_Size:',two_D_.size())

1-D to 2-D
tensor([1, 2, 3])
1D_Dimension: 1
1D_Size: torch.Size([3])
--------------------------------------------------
tensor([[1, 2, 3]])
2D_Dimension: 2
2D_Size: torch.Size([1, 3])
--------------------------------------------------
tensor([[1],
        [2],
        [3]])
2D_Dimension: 2
2D_Size: torch.Size([3, 1])


## tensor和np.array的關係轉換

In [27]:
import numpy as np
numpy_array = np.array([0,3.0,4.5])
torch_tensor = torch.from_numpy(numpy_array)
torch_Long_Tensor = torch.LongTensor(numpy_array)
numpy_from_torch = torch_tensor.numpy()
print('numpy_array:',numpy_array)
print('torch_tensor:',torch_tensor)
print('torch_long_tensor:',torch_Long_Tensor)
print('numpy_from_torch:',numpy_from_torch)

numpy_array: [0.  3.  4.5]
torch_tensor: tensor([0.0000, 3.0000, 4.5000], dtype=torch.float64)
torch_long_tensor: tensor([0, 3, 4])
numpy_from_torch: [0.  3.  4.5]


## tensor index and slice

In [30]:
c = torch.FloatTensor([20,1,2,3])
print(c[0])
print(c[0].item)
print(c[0].item())
c[1] = 2
c[2:] = torch.FloatTensor([4.0,5.5])
print(c)
c[[1,3]] = 100
print(c[1:])

tensor(20.)
<built-in method item of Tensor object at 0x7fd0d8118f98>
20.0
tensor([20.0000,  2.0000,  4.0000,  5.5000])
tensor([100.,   4., 100.])


## Basic Operation

In [34]:
print(torch.tensor([[1.0,2.0]]))
print(torch.tensor([[1.0,2.0]]).ndimension())
print(torch.tensor([[1.0,2.0]]).size())

tensor([[1., 2.]])
2
torch.Size([1, 2])


In [37]:
u = torch.tensor([[1.0],
                  [0.0]])
v = torch.tensor([[1.0],
                  [2.0]]).view(1,-1)
print(u)
print(v)
u_1D = torch.tensor([1.0,0.0])
v_1D = torch.tensor([1.0,2.0])
print(u+v)
print(u*v)
print(u+1)#Adding a constant to tensor
print(torch.dot(u_1D,v_1D))
print(torch.mm(u,v))#2D內積

tensor([[1.],
        [0.]])
tensor([[1., 2.]])
tensor([[2., 3.],
        [1., 2.]])
tensor([[1., 2.],
        [0., 0.]])
tensor([[2.],
        [1.]])
tensor(1.)
tensor([[1., 2.],
        [0., 0.]])


# 1-2

In [91]:
import pandas as pd
df = pd.DataFrame({'a':[1,2],'b':[3,3]})
print(df)
print('-'*50)
print(df.values)
print(torch.tensor(df.values))

#切割後維度改變
print(torch.tensor(df.values)[0][0].ndimension())
print(torch.tensor(df.values)[0].ndimension())
print(torch.tensor(df.values)[0:].ndimension())
print(torch.tensor(df.values)[0:][1])
print(torch.tensor(df.values)[0:][1].ndimension())

   a  b
0  1  3
1  2  3
--------------------------------------------------
[[1 3]
 [2 3]]
tensor([[1, 3],
        [2, 3]])
0
1
2
tensor([2, 3])
1


# 1-3

In [31]:
x = torch.tensor(2.0,requires_grad =True)
y = 2*x**3
#保留過去的梯度
y.backward(retain_graph=True)
print(y)
print(x.data)
print(x.grad)

tensor(16., grad_fn=<MulBackward0>)
tensor(2.)
tensor(24.)


In [30]:
x = torch.tensor(2.0,requires_grad =True)
z = x**2+2*x+1
z.backward()
print(z)
x.grad

tensor(9., grad_fn=<AddBackward0>)


tensor(6.)

## Partial Derivative

In [24]:
u = torch.tensor(1.0,requires_grad =True)
v = torch.tensor(2.0,requires_grad =True)

f = u*v+u**2
f.backward()
print(f)
print('Partial Derivative(u):',u.grad)
print('Partial Derivative(v):',v.grad)

tensor(3., grad_fn=<AddBackward0>)
Partial Derivative(u): tensor(4.)
Partial Derivative(v): tensor(1.)


# 1-4

In [2]:
import torch
from torch.utils.data import Dataset
torch.manual_seed(1)

## DataSets

In [3]:
torch.ones(10,2)[0]

tensor([1., 1.])

In [4]:
# Define class for dataset
# datasets 必備 __init__ __getitem__ __len__
class toy_set(Dataset):#繼承
    # Constructor with defult values 
    def __init__(self, length = 100, transform = None):
        self.len = length
        #二維的tensor
        self.x = 2 * torch.ones(length, 2)
        self.y = torch.ones(length, 1)
        self.transform = transform
     
    # Getter
    def __getitem__(self, index):
        sample = self.x[index], self.y[index]
        if self.transform:
            sample = self.transform(sample)     
        return sample
    
    # Get Length
    def __len__(self):
        return self.len

In [6]:
a = toy_set(length=10)
print('a.x:',a.x)
print('a.y:',a.y)
print(a[0])#__getitem__
print(len(a))

a.x: tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])
a.y: tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])
(tensor([2., 2.]), tensor([1.]))
tensor([2., 2.])
10


In [43]:
for i in range(3):
    x, y=a[i]
    print("index: ", i, '; x:', x, '; y:', y)

index:  0 ; x: tensor([2., 2.]) ; y: tensor([1.])
index:  1 ; x: tensor([2., 2.]) ; y: tensor([1.])
index:  2 ; x: tensor([2., 2.]) ; y: tensor([1.])


## Transforms

In [50]:
#transforms 必備 __init__ __call__
class add_mult(object):
    
    # Constructor
    def __init__(self, addx = 1, muly = 2):
        self.addx = addx
        self.muly = muly
    
    # Executor
    ##呼叫他會出什麼事
    def __call__(self, sample):
        print('出事')
        x = sample[0]
        y = sample[1]
        x = x + self.addx
        y = y * self.muly
        sample = x, y
        return x,y

In [51]:
a_m = add_mult()
data_set = toy_set()
print(a_m)
print(data_set)

### 使用Transform的兩種方法

In [52]:
for i in range(10):
    x, y = data_set[i]
    print('Index: ', i, 'Original x: ', x, 'Original y: ', y)
    x_, y_ = a_m(data_set[i])
    print('Index: ', i, 'Transformed x_:', x_, 'Transformed y_:', y_)

Index:  0 Original x:  tensor([2., 2.]) Original y:  tensor([1.])
出事
Index:  0 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([2.])
Index:  1 Original x:  tensor([2., 2.]) Original y:  tensor([1.])
出事
Index:  1 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([2.])
Index:  2 Original x:  tensor([2., 2.]) Original y:  tensor([1.])
出事
Index:  2 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([2.])
Index:  3 Original x:  tensor([2., 2.]) Original y:  tensor([1.])
出事
Index:  3 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([2.])
Index:  4 Original x:  tensor([2., 2.]) Original y:  tensor([1.])
出事
Index:  4 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([2.])
Index:  5 Original x:  tensor([2., 2.]) Original y:  tensor([1.])
出事
Index:  5 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([2.])
Index:  6 Original x:  tensor([2., 2.]) Original y:  tensor([1.])
出事
Index:  6 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([2.])
Index:  7 Ori

In [165]:
# Create a new data_set object with add_mult object as transform

cust_data_set = toy_set(transform = a_m)

In [166]:
for i in range(10):
    x, y = data_set[i]
    print('Index: ', i, 'Original x: ', x, 'Original y: ', y)
    x_, y_ = cust_data_set[i]
    print('Index: ', i, 'Transformed x_:', x_, 'Transformed y_:', y_)

Index:  0 Original x:  tensor([2., 2.]) Original y:  tensor([1.])
Index:  0 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([2.])
Index:  1 Original x:  tensor([2., 2.]) Original y:  tensor([1.])
Index:  1 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([2.])
Index:  2 Original x:  tensor([2., 2.]) Original y:  tensor([1.])
Index:  2 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([2.])
Index:  3 Original x:  tensor([2., 2.]) Original y:  tensor([1.])
Index:  3 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([2.])
Index:  4 Original x:  tensor([2., 2.]) Original y:  tensor([1.])
Index:  4 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([2.])
Index:  5 Original x:  tensor([2., 2.]) Original y:  tensor([1.])
Index:  5 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([2.])
Index:  6 Original x:  tensor([2., 2.]) Original y:  tensor([1.])
Index:  6 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([2.])
Index:  7 Original x:  tensor([2.,

In [21]:
x = torch.tensor(3.0,requires_grad=True)
y = x**4
z = y**2

In [17]:
z.backward()

In [18]:
y.grad

In [19]:
x.grad

tensor(17496.)

In [22]:
y.backward()
x.grad

tensor(108.)

In [39]:
import pandas as pd
a = pd.DataFrame({})
b = pd.DataFrame({'a':[1,2,3]})
pd.concat([a,b],axis=1)

a
0  1
1  2
2  3

In [41]:
b

a
0  1
1  2
2  3