# 2-1

In [4]:
import torch

In [2]:
w = torch.tensor(2.0, requires_grad = True)
b = torch.tensor(-1.0, requires_grad = True)

In [3]:
def forward(x):
    yhat = w * x + b
    return yhat

In [4]:
x = torch.tensor([[1.0]])
yhat = forward(x)
print("The prediction: ", yhat)

The prediction:  tensor([[1.]], grad_fn=<AddBackward0>)


In [5]:
x = torch.tensor([[1.0], [2.0]])
print("The shape of x: ", x.shape)

The shape of x:  torch.Size([2, 1])


In [6]:
yhat = forward(x)
print("The prediction: ", yhat)

The prediction:  tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)


## class linear

In [5]:
#nueral network
from torch.nn import Linear

In [9]:
torch.manual_seed(1)

In [20]:
lr = Linear(in_features=1, out_features=2, bias=True)
print("Parameters w and b: ", list(lr.parameters()))

Parameters w and b:  [Parameter containing:
tensor([[0.9356],
        [0.6881]], requires_grad=True), Parameter containing:
tensor([-0.4937, -0.4596], requires_grad=True)]


In [21]:
print("Python dictionary: ",lr.state_dict())
print("keys: ",lr.state_dict().keys())
print("values: ",lr.state_dict().values())

Python dictionary:  OrderedDict([('weight', tensor([[0.9356],
        [0.6881]])), ('bias', tensor([-0.4937, -0.4596]))])
keys:  odict_keys(['weight', 'bias'])
values:  odict_values([tensor([[0.9356],
        [0.6881]]), tensor([-0.4937, -0.4596])])


In [22]:
print("weight:",lr.weight)
print("bias:",lr.bias)

weight: Parameter containing:
tensor([[0.9356],
        [0.6881]], requires_grad=True)
bias: Parameter containing:
tensor([-0.4937, -0.4596], requires_grad=True)


In [23]:
x = torch.tensor([[1.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[0.4418, 0.2285]], grad_fn=<AddmmBackward0>)


In [24]:
x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[0.4418, 0.2285],
        [1.3774, 0.9165]], grad_fn=<AddmmBackward0>)


## Build Custom Modules

In [80]:
from torch import nn
class LR(nn.Module):
    def __init__(self, input_size, output_size):
        super(LR,self).__init__()#等同於super().__init__()
        self.linear = nn.Linear(input_size, output_size)
    def forward(self,x):
        out = self.linear(x)
        return out

In [81]:
lr = LR(1, 1)
print("The parameters: ", list(lr.parameters()))
print("Linear model: ", lr.linear)

The parameters:  [Parameter containing:
tensor([[-0.3724]], requires_grad=True), Parameter containing:
tensor([-0.6040], requires_grad=True)]
Linear model:  Linear(in_features=1, out_features=1, bias=True)


In [82]:
x = torch.tensor([[1.0]])
yhat = lr(x)
print(lr(x))
print("The prediction: ", yhat)

tensor([[-0.9764]], grad_fn=<AddmmBackward0>)
The prediction:  tensor([[-0.9764]], grad_fn=<AddmmBackward0>)


In [18]:
x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[0.2755],
        [0.0816]], grad_fn=<AddmmBackward0>)


In [25]:
print("Python dictionary: ", lr.state_dict())
print("keys: ",lr.state_dict().keys())
print("values: ",lr.state_dict().values())

Python dictionary:  OrderedDict([('linear.weight', tensor([[-0.2057]])), ('linear.bias', tensor([0.5087]))])
keys:  odict_keys(['linear.weight', 'linear.bias'])
values:  odict_values([tensor([[-0.2057]]), tensor([0.5087])])


# 自己測試nn.linear運作方式

In [5]:
from torch.nn import Linear
import torch
lr = Linear(in_features=2, out_features=3, bias=True)

In [6]:
list(lr.parameters())#x*wT+b

[Parameter containing:
 tensor([[-0.4845,  0.0746],
         [-0.5828,  0.5705],
         [ 0.1273, -0.4341]], requires_grad=True),
 Parameter containing:
 tensor([-0.2240, -0.4618,  0.4466], requires_grad=True)]

In [64]:
lr.state_dict()

OrderedDict([('weight',
              tensor([[ 0.4568, -0.2453],
                      [ 0.2312,  0.5858],
                      [ 0.4108,  0.0647],
                      [-0.6675, -0.4238]])),
             ('bias', tensor([ 0.0163, -0.4421, -0.2376, -0.0695]))])

In [66]:
lr(torch.tensor([[2.0,4.0]]))

tensor([[-0.0515,  2.3635,  0.8428, -3.0996]], grad_fn=<AddmmBackward0>)